### ISSUE TITLE
Pretty Urls - should have trailing slash?

### ISSUE THREAD

**Issue by Alshie** [netlify-labs/netlify-plugin-sitemap#10]
> Pretty urls a.k.a. site.com/index.html being turned into site.com/ is on by default.

For me in practice the end result of pretty urls was to produce urls like

site.com/index.html > site.com
site.com/folder/index.html > site.com/folder

It's a super easy fix and I'm happy to do a pull request for this, not sure if this is the desired behaviour though? I would generally always include the tailing slash - is there a reason not to? Should it be an option to include or exclude?

**Comment by andreslucero** [comment]
I definitely expected the trailing slash as well, since Netlify will redirect the non-trailing slash version to the trailing-slash version. The current configuration results in all of the URLs in the sitemap effectively being "wrong" because they cause a 301 redirect.

**Comment by mornir** [comment]
I had the same expectation as @andreslucero  
Please make it the default or provide an option 🥺

**Comment by joebailey26** [comment]
This definitely needs fixing

**Comment by erezrokah** [comment]
Fixes via https://github.com/netlify-labs/netlify-plugin-sitemap/pull/13

**Comment by jouni-kantola** [comment]
@erezrokah Do you know how long/what it takes for Netlify to pick up the updated plugin? When deploying version `0.3.4` is still being used (see log below). Using `netlify-cli` locally  works fine.
```
9:40:53 AM: ┌────────────────────────────────────────────────────────────────┐
9:40:53 AM: │ Plugin "@netlify/plugin-sitemap" invalid input "trailingSlash" │
9:40:53 AM: └────────────────────────────────────────────────────────────────┘
9:40:53 AM: ​
9:40:53 AM:   Error message
9:40:53 AM:   Unknown inputs for plugin "@netlify/plugin-sitemap": "trailingSlash"
9:40:53 AM:   Plugin inputs should be one of: "baseUrl", "buildDir", "exclude", "prettyURLs"
9:40:53 AM:   Check your plugin configuration to be sure that:
9:40:53 AM:     - the input name is spelled correctly
9:40:53 AM:     - the input is included in the plugin's available configuration options
    - the plugin's input requirements have not changed
​
9:40:53 AM:   Plugin inputs
9:40:53 AM:   buildDir: _site
9:40:53 AM:   prettyURLs: true
9:40:53 AM:   trailingSlash: true
9:40:53 AM: ​
9:40:53 AM:   Plugin details
9:40:53 AM:   Package:        @netlify/plugin-sitemap
9:40:53 AM:   Version:        0.3.4
9:40:53 AM:   Repository:     git+https://github.com/netlify-labs/netlify-plugin-sitemap.git
9:40:53 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-sitemap
9:40:53 AM:   Report issues:  https://github.com/netlify-labs/netlify-plugin-sitemap/issues
9:40:53 AM: ​
9:40:53 AM:   Error location
9:40:53 AM:   While loading "@netlify/plugin-sitemap" from netlify.toml
```

**Comment by erezrokah** [comment]
Hi @jouni-kantola, the PR to update the plugin is still up https://github.com/netlify/plugins/pull/158

You can install the latest version using `npm install --save-dev "@netlify/plugin-sitemap"` until the PR is merged.

**Comment by jouni-kantola** [comment]
Thanks for pinging back, @erezrokah. Referencing as dev dependency worked well. ✅
