### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by IbrahimTGD** [netlify-labs/netlify-plugin-sitemap#15]
Hi. The plugin isnt working. https://papagames.netlify.app/sitemap.xml nothing is showing up.   This is my build command       8:16:16 PM: Build ready to start     8:16:18 PM: build-image version: 1c94a9fe0dfb4e98b234e71cc1bddd4d658efb98     8:16:18 PM: build-image tag: v3.3.13     8:16:18 PM: buildbot version: 16afa782e76be01c032045e13544252dd035664b     8:16:19 PM: Fetching cached dependencies     8:16:19 PM: Starting to download cache of 300.8MB     8:16:24 PM: Finished downloading cache in 5.501002541s     8:16:24 PM: Starting to extract cache     8:16:32 PM: Finished extracting cache in 7.831199873s     8:16:32 PM: Finished fetching cache in 13.422774972s     8:16:32 PM: Starting to prepare the repo for build     8:16:32 PM: Preparing Git Reference refs/heads/master     8:16:35 PM: Starting build script     8:16:35 PM: Installing dependencies     8:16:35 PM: Started restoring cached node version     8:16:40 PM: Finished restoring cached node version     8:16:41 PM: v10.20.1 is already installed.     8:16:42 PM: Now using node v10.20.1 (npm v6.14.4)     8:16:42 PM: Started restoring cached build plugins     8:16:42 PM: mv: cannot move '/opt/build/cache/.netlify/plugins' to '/opt/build/repo/.netlify/plugins': No such file or directory     8:16:42 PM: Finished restoring cached build plugins     8:16:42 PM: Attempting ruby version 2.6.2, read from environment     8:16:43 PM: Using ruby version 2.6.2     8:16:44 PM: Using PHP version 5.6     8:16:44 PM: 5.2 is already installed.     8:16:44 PM: Using Swift version 5.2     8:16:44 PM: Started restoring cached go cache     8:16:44 PM: Finished restoring cached go cache     8:16:44 PM: go version go1.12 linux/amd64     8:16:44 PM: go version go1.12 linux/amd64     8:16:44 PM: Installing missing commands     8:16:44 PM: Verify run directory     8:16:46 PM: ​     8:16:46 PM: ┌─────────────────────────────┐     8:16:46 PM: │        Netlify Build        │     8:16:46 PM: └─────────────────────────────┘     8:16:46 PM: ​     8:16:46 PM: ❯ Version     8:16:46 PM:   @netlify/build 0.4.26     8:16:46 PM: ​     8:16:46 PM: ❯ Flags     8:16:46 PM:   mode: buildbot     8:16:46 PM: ​     8:16:46 PM: ❯ Current directory     8:16:46 PM:   /opt/build/repo     8:16:46 PM: ​     8:16:46 PM: ❯ Config file     8:16:46 PM:   /opt/build/repo/netlify.toml     8:16:46 PM: ​     8:16:46 PM: ❯ Context     8:16:46 PM:   production     8:16:46 PM: ​     8:16:46 PM: ❯ Installing plugins     8:16:46 PM:    - @netlify/plugin-sitemap     8:16:52 PM: ​     8:16:52 PM: ❯ Loading plugins     8:16:52 PM:    - @netlify/plugin-sitemap@0.3.3     8:16:52 PM: ​     8:16:52 PM: ┌─────────────────────────────────────────────────────┐     8:16:52 PM: │ 1. onPostBuild command from @netlify/plugin-sitemap │     8:16:52 PM: └─────────────────────────────────────────────────────┘     8:16:52 PM: ​     8:16:52 PM: Creating sitemap from files...     8:16:52 PM: Sitemap Built! sitemap.xml     8:16:52 PM: ​     8:16:52 PM: (@netlify/plugin-sitemap onPostBuild completed in 45ms)     8:16:52 PM: ​     8:16:52 PM: ┌─────────────────────────────┐     8:16:52 PM: │   Netlify Build Complete    │     8:16:52 PM: └─────────────────────────────┘     8:16:52 PM: ​     8:16:52 PM: (Netlify Build completed in 6.5s)     8:16:52 PM: Caching artifacts     8:16:52 PM: Started saving node modules     8:16:52 PM: Finished saving node modules     8:16:52 PM: Started saving pip cache     8:16:59 PM: Finished saving pip cache     8:16:59 PM: Started saving emacs cask dependencies     8:16:59 PM: Finished saving emacs cask dependencies     8:16:59 PM: Started saving maven dependencies     8:16:59 PM: Finished saving maven dependencies     8:16:59 PM: Started saving boot dependencies     8:16:59 PM: Finished saving boot dependencies     8:16:59 PM: Started saving go dependencies     8:16:59 PM: Finished saving go dependencies     8:16:59 PM: Build script success     8:16:59 PM: Starting to deploy site from '/'     8:16:59 PM: Creating deploy tree      8:17:00 PM: Creating deploy upload records     8:17:00 PM: 1 new files to upload     8:17:00 PM: 0 new functions to upload     8:17:00 PM: Starting post processing     8:17:00 PM: Post processing done     8:17:00 PM: Site is live     8:18:03 PM: Finished processing build request in 1m44.217402851s  Is this right?
--

**Comment by andreslucero** [comment]
@IbrahimTGD the `sitemap.xml` file is being generated, but it's not in your web root directory.

Make sure your `netlify.toml` file specifies the correct `buildDir` where you want the sitemap file to be generated:

https://github.com/netlify-labs/netlify-plugin-sitemap#configuration

This is most likely the same directory where the `index.php`, `favicon.ico` and `robots.txt` files live.

**Comment by erezrokah** [comment]
Closing as stale. If still relevant please comment with a reproduction.
