### ISSUE TITLE
missing manifest.yml

### ISSUE THREAD

**Issue by xier892** [netlify-labs/netlify-plugin-sitemap#17]
as of v0.3.4, deploying fails:

`8:12:20 AM:   Error message
8:12:20 AM:   Error: This plugin is missing a "manifest.yml".
8:12:20 AM:   Please see the documentation at https://github.com/netlify/build#anatomy-of-a-plugin`

**Comment by erezrokah** [comment]
Closing this as stale. If this is still an issue, please update to the latest version
