### ISSUE TITLE
sitemap.xml wrong/empty if buildDir is top-level directory

### ISSUE THREAD

**Issue by tomkit** [netlify-labs/netlify-plugin-sitemap#23]
If your public assets are in the top-level of the directory and you set buildDir to: "" or "." or "./" or "/". It results in any of (1) missing sitemap.xml, (2) incomplete sitemap.xml, (3) build error

**Comment by erezrokah** [comment]
Probably related to https://github.com/netlify-labs/netlify-plugin-sitemap/pull/11

**Comment by erezrokah** [comment]
@tomkit can you confirm this still happens with the latest version `0.5.0`?

**Comment by erezrokah** [comment]
Closing as stale. Please comment if still relevant
