### ISSUE TITLE
[Feature Request] Possibility to configure properties like changefreq or priority

### ISSUE THREAD

**Issue by ricardofiorani** [netlify-labs/netlify-plugin-sitemap#24]
The plugin today appears to have fixed values as:
```
<changefreq>weekly</changefreq>
<priority>0.8</priority>
```
It would be nice to be able to configure these for each entry, or at least, the default value for all.

**Comment by cebreus** [comment]
This is duplicity for #22, but better described.

**Comment by erezrokah** [comment]
Fixed via #25
