### ISSUE TITLE
Plugin still building sitemap even when code not referenced

### ISSUE THREAD

**Issue by AttractMore** [netlify-labs/netlify-plugin-sitemap#27]
Hi.
This is an odd one. I tried using the sitemap plugin but decided against it so deleted reference to it from my netlify.toml. However, the site map generated is still in the Hugo public directory and it continues to be updated when I change the site. How do I stop this?

Also the plugin doesn't seem to respect the fact that some pages are set to noindex.

Any help appreciated.

**Comment by erezrokah** [comment]
Hi @AttractMore, can you make sure it is not installed from the UI here `https://app.netlify.com/teams/<your-teamid>/plugins`

**Comment by AttractMore** [comment]
Hi @erezrokah . Thanks for quick reply. That URL gives me a list of all plugins but the sitemap plugin is not showing as installed there.

**Comment by erezrokah** [comment]
That's very odd, do you still have it as a dependency? Can you share a repo/logs/site URL? Can you try installing, then uninstalling?

 

> Also the plugin doesn't seem to respect the fact that some pages are set to noindex.

Can you open a new feature request for this?

**Comment by AttractMore** [comment]
OK, I installed the plugin again via netlify.toml with
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  changeFreq = "monthly"
  priority = 0.8
The build failed
Plugin "@netlify/plugin-sitemap" invalid input "changeFreq"

Unknown inputs for plugin "@netlify/plugin-sitemap": "changeFreq", "priority" Plugin inputs should be one of: "baseUrl", "buildDir", "exclude", "prettyURLs" Check your plugin configuration to be sure that:

    the input name is spelled correctly
    the input is included in the plugin's available configuration options
    the plugin's input requirements have not changed

Plugin inputs buildDir: public changeFreq: monthly priority: 0.8

SO I deleted the last 2 lines and the site deployed fine. Sitemap was updated although no reference to this in the deploy log.
Priority on all URLs now set to 0.8 and changefreq set to weekly!! But urls had no trailing /

I then removed the reference to the Sitemap plugin from netlify.toml and rebuilt the site. The sitemap was regenerated with no reference to changefreq or priority but the urls now all have trailling /

**Comment by erezrokah** [comment]
Thanks, that helps.
`changefreq` was always set to `weekly` https://github.com/netlify-labs/netlify-plugin-sitemap/blob/268cbdb70fa0051ea62faa7b3f859f0a79ce6151/make_sitemap.js#L24 and can now be configured, but you'll need to install the latest version of the plugin using `npm install --save-dev @netlify/plugin-sitemap`.

Can you share the content of your `package.json`? If you remove the plugin from there and run `npm install` it should not run

**Comment by AttractMore** [comment]
There is no package.json on this HUGO site.  I originally installed the sitemap plugin via the Install button on the Netlify plugins page for the site

**Comment by erezrokah** [comment]
Can you share a deploy log, site id and deploy id? If the plugin doesn't show up as installed in the UI (nor installed as a dependency/`netlify.toml`) and is still running that might not be related to the plugin itself, but to the build system.

**Comment by AttractMore** [comment]
site is oradesign.netlify.app

11:41:01 AM: Build ready to start
11:41:03 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
11:41:03 AM: build-image tag: v3.4.1
11:41:03 AM: buildbot version: 0e3cc7aef5c33f731b54ed4b65d515eaab821679
11:41:03 AM: Fetching cached dependencies
11:41:04 AM: Starting to download cache of 79.7MB
11:41:05 AM: Finished downloading cache in 1.201283387s
11:41:05 AM: Starting to extract cache
11:41:07 AM: Finished extracting cache in 2.238168761s
11:41:07 AM: Finished fetching cache in 3.456720095s
11:41:07 AM: Starting to prepare the repo for build
11:41:07 AM: Preparing Git Reference refs/heads/master
11:41:09 AM: Starting build script
11:41:09 AM: Installing dependencies
11:41:09 AM: Python version set to 2.7
11:41:10 AM: Started restoring cached node version
11:41:12 AM: Finished restoring cached node version
11:41:13 AM: v12.18.0 is already installed.
11:41:13 AM: Now using node v12.18.0 (npm v6.14.4)
11:41:13 AM: Started restoring cached build plugins
11:41:13 AM: Finished restoring cached build plugins
11:41:13 AM: Attempting ruby version 2.7.1, read from environment
11:41:15 AM: Using ruby version 2.7.1
11:41:15 AM: Using PHP version 5.6
11:41:15 AM: 5.2 is already installed.
11:41:15 AM: Using Swift version 5.2
11:41:15 AM: Started restoring cached go cache
11:41:15 AM: Finished restoring cached go cache
11:41:15 AM: go version go1.14.4 linux/amd64
11:41:15 AM: go version go1.14.4 linux/amd64
11:41:15 AM: Installing missing commands
11:41:15 AM: Verify run directory
11:41:16 AM: ​
11:41:16 AM: ┌─────────────────────────────┐
11:41:16 AM: │        Netlify Build        │
11:41:16 AM: └─────────────────────────────┘
11:41:16 AM: ​
11:41:16 AM: ❯ Version
11:41:16 AM:   @netlify/build 4.6.3
11:41:16 AM: ​
11:41:16 AM: ❯ Flags
11:41:16 AM:   deployId: 5f7aea2dc3646e000859ed86
11:41:16 AM:   mode: buildbot
11:41:16 AM: ​
11:41:16 AM: ❯ Current directory
11:41:16 AM:   /opt/build/repo
11:41:16 AM: ​
11:41:16 AM: ❯ Config file
11:41:16 AM:   /opt/build/repo/netlify.toml
11:41:16 AM: ​
11:41:16 AM: ❯ Context
11:41:16 AM:   production
11:41:16 AM: ​
11:41:16 AM: ┌───────────────────────────────────┐
11:41:16 AM: │ 1. Build command from Netlify app │
11:41:16 AM: └───────────────────────────────────┘
11:41:16 AM: ​
11:41:16 AM: $ hugo
11:41:17 AM: Building sites …
11:41:17 AM:                    | EN
11:41:17 AM: +------------------+----+
11:41:17 AM:   Pages            | 32
11:41:17 AM:   Paginator pages  |  0
11:41:17 AM:   Non-page files   |  0
11:41:17 AM:   Static files     | 78
11:41:17 AM:   Processed images |  0
11:41:17 AM:   Aliases          |  0
11:41:17 AM:   Sitemaps         |  1
11:41:17 AM:   Cleaned          |  0
11:41:17 AM: Total in 150 ms
11:41:17 AM: ​
11:41:17 AM: (build.command completed in 967ms)
11:41:17 AM: ​
11:41:17 AM: ┌─────────────────────────────┐
11:41:17 AM: │   Netlify Build Complete    │
11:41:17 AM: └─────────────────────────────┘
11:41:17 AM: ​
11:41:17 AM: (Netlify Build completed in 1s)
11:41:17 AM: Caching artifacts
11:41:17 AM: Started saving build plugins
11:41:17 AM: Finished saving build plugins
11:41:17 AM: Started saving pip cache
11:41:18 AM: Finished saving pip cache
11:41:18 AM: Started saving emacs cask dependencies
11:41:18 AM: Finished saving emacs cask dependencies
11:41:18 AM: Started saving maven dependencies
11:41:18 AM: Finished saving maven dependencies
11:41:18 AM: Started saving boot dependencies
11:41:18 AM: Finished saving boot dependencies
11:41:18 AM: Started saving go dependencies
11:41:18 AM: Finished saving go dependencies
11:41:18 AM: Build script success
11:41:18 AM: Starting to deploy site from 'public'
11:41:18 AM: Creating deploy tree 
11:41:18 AM: Creating deploy upload records
11:41:18 AM: 0 new files to upload
11:41:18 AM: 0 new functions to upload
11:41:18 AM: Starting post processing
11:41:18 AM: Post processing - HTML
11:41:19 AM: Post processing - header rules
11:41:19 AM: Post processing - redirect rules
11:41:19 AM: Post processing done
11:41:19 AM: Site is live
11:41:29 AM: Finished processing build request in 25.627617946s

**Comment by erezrokah** [comment]
Looks like the sitemap is generated by `hugo` and not this plugin.
If the plugin is invoked the logs should reflect that.
Can you try disabling sitemap generation in `hugo`? This might help https://kodify.net/hugo/pages/disable-hugo-sitemap/

**Comment by AttractMore** [comment]
That's it! I hadn't realised that HUGO was creating a sitemap and appreciate your persistence in getting to the bottom of this issue.
Thanks

**Comment by erezrokah** [comment]
Closing the issue. Please comment if you have any other issues.
