### ISSUE TITLE
sitemap plugin going to 404 not found

### ISSUE THREAD

**Issue by nanojuna** [netlify-labs/netlify-plugin-sitemap#29]
sitemap plugin going to 404 not found, before is normal when try to new build is gone
what is wrong?

**Comment by erezrokah** [comment]
Hi @nanojuna, can you please share a reproduction scenario or a repo with the issue?
I'm finding it hard to understand the error you're experiencing.

**Comment by erezrokah** [comment]
Closing this as I believe it is related to https://github.com/netlify-labs/netlify-plugin-sitemap/issues/28
