### ISSUE TITLE
v0.5.1 doesn't work if buildDir is set to `/`

### ISSUE THREAD

**Issue by ibrahimBeladi** [netlify-labs/netlify-plugin-sitemap#33]
**Describe the bug**

v0.5.1 is broken with static non-npm website.

**To Reproduce**

1. Make a non-npm website
2. Deploy it to Netlify
3. Error, see that the sitemap file is missing...

**Expected behavior**

Works.

**Additional context**
In v0.5.0 it worked fine:
```
12:30:30 PM: ❯ Loading plugins
12:30:30 PM:    - @netlify/plugin-sitemap@0.5.0 from netlify.toml
12:30:30 PM:    - ....
12:30:30 PM: ​
12:30:30 PM: ┌─────────────────────────────────────────────────────┐
12:30:30 PM: │ 1. onPostBuild command from @netlify/plugin-sitemap │
12:30:30 PM: └─────────────────────────────────────────────────────┘
12:30:30 PM: ​
12:30:30 PM: Creating sitemap from files...
12:30:30 PM: Sitemap Built! sitemap.xml
12:30:30 PM: ​
12:30:30 PM: (@netlify/plugin-sitemap onPostBuild completed in 45ms)
```

However, in v0.5.1, it broke:
```
12:40:45 PM: ❯ Loading plugins
12:40:45 PM:    - @netlify/plugin-sitemap@0.5.1 from netlify.toml
12:40:45 PM:    - ....
12:40:46 PM: ​
12:40:46 PM: ┌─────────────────────────────────────────────────────┐
12:40:46 PM: │ 1. onPostBuild command from @netlify/plugin-sitemap │
12:40:46 PM: └─────────────────────────────────────────────────────┘
12:40:46 PM: ​
12:40:46 PM: Creating sitemap from files...
12:40:46 PM: ​
12:40:46 PM: ┌─────────────────────────────────────────────────┐
12:40:46 PM: │ Plugin "@netlify/plugin-sitemap" internal error │
12:40:46 PM: └─────────────────────────────────────────────────┘
12:40:46 PM: ​
12:40:46 PM:   Error message
12:40:46 PM:   Error: EACCES: permission denied, scandir '//root'
12:40:46 PM: ​
12:40:46 PM:   Plugin details
12:40:46 PM:   Package:        @netlify/plugin-sitemap
12:40:46 PM:   Version:        0.5.1
12:40:46 PM:   Repository:     git+https://github.com/netlify-labs/netlify-plugin-sitemap.git
12:40:46 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-sitemap
12:40:46 PM:   Report issues:  https://github.com/netlify-labs/netlify-plugin-sitemap/issues
12:40:46 PM: ​
12:40:46 PM:   Error location
12:40:46 PM:   In "onPostBuild" event in "@netlify/plugin-sitemap" from netlify.toml
12:40:46 PM: ​
12:40:46 PM:   Error properties
12:40:46 PM:   { errno: -13, code: 'EACCES', syscall: 'scandir', path: '//root' }
12:40:46 PM: ​
12:40:46 PM:   Resolved config
12:40:46 PM:   build:
12:40:46 PM:     publish: /opt/build/repo
12:40:46 PM:   plugins:
12:40:46 PM:     - inputs:
12:40:46 PM:         prettyURLs: true
12:40:46 PM:         trailingSlash: true
12:40:46 PM:       origin: config
12:40:46 PM:       package: '@netlify/plugin-sitemap'
......
```

**Comment by ibrahimBeladi** [comment]
Also, is it possible to specify a version for the plugin?

**Comment by erezrokah** [comment]
Hi @ibrahimBeladi, can you share how you're installing the plugin? Via Netlify UI or `netlify.toml`?
If from `netlify.toml` can you share that configuration?
If from Netlify UI can you share the build settings, specifically the publish directory?

**Comment by ibrahimBeladi** [comment]
```
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true
  trailingSlash = true

  buildDir = "/"
  exclude = [
    // ...
  ]

[[plugins]]
package = "netlify-plugin-submit-sitemap"
```

**Comment by erezrokah** [comment]
Can you try changing `buildDir = "/"` to `buildDir = "./"` and let me know if that works?

**Comment by ibrahimBeladi** [comment]
It worked!

**Comment by erezrokah** [comment]
Keeping this issue open - the underlying issue is that we need to reinstate https://github.com/netlify-labs/netlify-plugin-sitemap/pull/11 without breaking excludes (see https://github.com/netlify-labs/netlify-plugin-sitemap/pull/31)

**Comment by ethanosullivan** [comment]
> Can you try changing `buildDir = "/"` to `buildDir = "./"` and let me know if that works?

I had an issue with my Sitemap recently as well. When I tried to visit it, I would end up with a 404 page. I set the `buildDir` to the example above and that loads my sitemap. However, it's blank. I changed it to `buildDir = "publish"` like the documentation, but I get the 404 again.

Here's my config:

```
# Sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "publish"
prettyURLs = true
trailingSlash = true
exclude = [
    "**/404.html"
]
```

Please let me know the default `buildDir` to use.

**Comment by erezrokah** [comment]
Hi @ethanosullivan, I updated the issue title to reflect the underlying problem.

Do you mind opening a new issue for your case? Please share (in addition to your `netlify.toml`) the structure of your repo and where built files are placed.

**Comment by ethanosullivan** [comment]
Hey @erezrokah - I just created the new issue for you: #34

**Comment by ibrahimBeladi** [comment]
I just noticed, it misses the root index file, for example: `domain.com/`

**Comment by erezrokah** [comment]
This should be fixed by https://github.com/netlify-labs/netlify-plugin-sitemap/pull/41 and https://github.com/netlify-labs/netlify-plugin-sitemap/pull/42
