### ISSUE TITLE
URLs in sitemap are incomplete

### ISSUE THREAD

**Issue by theseoguy** [netlify-labs/netlify-plugin-sitemap#36]
Hello

The URLs in sitemap appear this way: <loc>https://mysite.com/example-page</loc> while actual URL is https://mysite.com/example-page/. 

As the result Ahrefs, indicates "3XX redirect in sitemap"

So one missing slash (/) causes much trouble.

**Comment by erezrokah** [comment]
Hi @theseoguy can you try setting `trailingSlash = true`?
See https://github.com/netlify-labs/netlify-plugin-sitemap#pretty-urls

**Comment by erezrokah** [comment]
Closing this per lack of response

**Comment by theseoguy** [comment]
Oh yes sorry. Problem was not in the plugin but in pretty URL on Netlify :)
