### ISSUE TITLE
Where is the generated sitemap.xml located?

### ISSUE THREAD

**Issue by 684efs3** [netlify-labs/netlify-plugin-sitemap#45]
Where is the generated sitemap.xml located? I used this plugin and it seems like it works, but I cannot find the sitemap.xml that is generated. It is not located at root/sitemap.xml.

**Comment by erezrokah** [comment]
Hi @684efs3, it should be generated under the publish directory (where you html files are):
https://github.com/netlify-labs/netlify-plugin-sitemap/blob/3053ec90c267381a705313ddda06f82353668260/make_sitemap.js#L102

**Comment by 684efs3** [comment]
Thanks a lot!!
