### ISSUE TITLE
Question: build step

### ISSUE THREAD

**Issue by steveoh** [netlify-labs/netlify-plugin-sitemap#5]
Does the website being built's stack matter when using this plugin?

Would this work for sites created with jekyll, hugo, ghost, etc?

I think your readme could be more clear on the goals of this plugin.

**Comment by mornir** [comment]
As long as all pages are statically generated at build time (= no SPA), this plugin should work with any SSG.

**Comment by erezrokah** [comment]
Closing this as resolved. Thanks @mornir
