### ISSUE TITLE
Not working with google search console

### ISSUE THREAD

**Issue by asfi50** [netlify-labs/netlify-plugin-sitemap#69]
Generated Sitemap cant be fetched by google! 

**To Reproduce**

1. Fork the repository  `https://github.com/<owner>/<repo>/`
2. Deploy it to Netlify
3. See that the sitemap file is missing...

**Expected behavior**

**Additional context**

**Comment by erezrokah** [comment]
Hi @asfi50 do you mind feeling in the blanks from the issue template?
That makes it much easier to understand the issue you're facing.

**Comment by asfi50** [comment]
Hmm.... your plugin is working fine but I dont know why google is refusing to fetch it. 

On the other hand Bing successfully fetched it. So this is the issue..... I think the problem is in Google

**Comment by erezrokah** [comment]
Thank you for following up.
Pending more information I'm closing this issue.
