### ISSUE TITLE
Netlify build fails with error:  Invalid event 'makeSitemap'

### ISSUE THREAD

**Issue by trinodal** [netlify-labs/netlify-plugin-sitemap#7]
Error message
  Error: Invalid event 'makeSitemap'.
  Please use a valid event name. One of:
   - onInit
   - onPreBuild
   - onBuild
   - onPostBuild
   - onSuccess
   - onError
   - onEnd
​
  Plugin details
  ID:             @netlify/plugin-sitemap
  Version:        0.2.1
  npm link:       https://www.npmjs.com/package/@netlify/plugin-sitemap
​
  Error location
  While loading npm package "@netlify/plugin-sitemap"

**Comment by zackseuberling** [comment]
I believe this has been resolved

**Comment by trinodal** [comment]
As of `v0.3.0` this has been resolved. Thank you.
