### ISSUE TITLE
bug: v0.8.0 fails with `EACCES: permission denied, scandir '/root'`, worked on 0.7.0

### ISSUE THREAD

**Issue by shamaayilahmed** [netlify-labs/netlify-plugin-sitemap#71]
I had deployed a plain JavaScript site and suddenly this error shows up, help me out here.
 Lately I changed http based push to ssh in github

```
Plugin "@netlify/plugin-sitemap" internal error               

Error message
Error: EACCES: permission denied, scandir '/root'

   Plugin details
Package:        @netlify/plugin-sitemap
Version:        0.8.0
Repository:     git+https://github.com/netlify-labs/netlify-plugin-sitemap.git
npm link:       https://www.npmjs.com/package/@netlify/plugin-sitemap
Report issues:  https://github.com/netlify-labs/netlify-plugin-sitemap/issues
​
Error location
In "onPostBuild" event in "@netlify/plugin-sitemap" from Netlify app​
Error properties
{ errno: -13, code: 'EACCES', syscall: 'scandir', path: '/root' }​
Resolved config
build:
publish: /opt/build/repo
plugins:
- inputs: {}
origin: ui
package: '@netlify/plugin-sitemap'
```

**Comment by erezrokah** [comment]
Hi @shamaayilahmed, can you share a public repo reproducing the issue?
Also, can you share if the publish directory is configured under the site settings in Netlify UI?

**Comment by shamaayilahmed** [comment]
@erezrokah Actually that's my portfolio and it's set as private. 

I just went through the recent successful build there it was sitemap plugin v0.7.0 now it's 0.8.0, So of that's the problem.

**Comment by erezrokah** [comment]
Thanks for the additional information. Is your site deploying from the root folder of the repo? I suspect that might be related. If so I'll try to create a reproduction based on that.

**Comment by shamaayilahmed** [comment]
Yes it's deployed from root folder itself so far.

**Comment by shamaayilahmed** [comment]
Whoa, I just installed the sitemap-plugin@0.7.0 locally and now the site successfully builds and deploys. So probably that's the v0.8.0 doing this glitch.
