### ISSUE TITLE
not able to install the plugin

### ISSUE THREAD

**Issue by Akash7738** [netlify-labs/netlify-plugin-sitemap#77]
**Describe the bug**

**To Reproduce**

1. Fork the repository  `https://github.com/<owner>/<repo>/`
2. Deploy it to Netlify
3. See that the sitemap file is missing...

**Expected behavior**

**Additional context**

**Comment by erezrokah** [comment]
Hi @Akash7738, can you please follow the issue template and share more information on the issue you're experiencing?

**Comment by IanVS** [comment]
Seems like this issue should be closed?
