### ISSUE TITLE
Readme confusion

### ISSUE THREAD

**Issue by jnfaerch** [netlify-labs/netlify-plugin-sitemap#9]
From readme:
```
Configure the plugin buildDir. Default is the publish directory from your site build settings.

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
```
It says: `Default is the publish directory...`

But the example says
```
  [plugins.inputs]
  buildDir = "public"
```
I believe the text should be: **Default is the public directory...**

If that assumption is not correct I would say it needs further explanation :)

**Comment by zackseuberling** [comment]
the way I interpret the documentation is: this plugin will use the directory where your site is built (or published, to use the same word in the documentation).

let's say you're using eleventy to build your site, but have changed the default build directory from `_site` to `public`, and in your `netlify.toml` file you have something like

```toml
[build]
  command = "yarn build"
  publish = "public"
```

based on the README, I would expect the plugin to use `public` by default

I can't think of a use case off the top of my head why someone would want the sitemap file to be generated in a directory that is different from their publish directory, but I'm sure there are reasons. perhaps clarifying that use case in the README would be more helpful than the current information
